BACKGROUND_COLOR = "#d9d9d9"
FOREGROUND_COLOR = "#fff"
TEXT_COLOR_LIGHT = "#fff"
TEXT_COLOR_DARK = "#000"

CONFIRM_BUTTON_COLOR = "#4CAF50"  # Green
CONFIRM_BUTTON_HOVER_COLOR = "#45a049"  # Darker green
CONFIRM_BUTTON_ACTIVE_COLOR = "#3e8e41"  # Even darker green
CONFIRM_BUTTON_BORDER_COLOR = "#3e8e41"  # Darker green
CONFIRM_BUTTON_BORDER_HOVER_COLOR = "#2e7031"  # Darker green
CONFIRM_BUTTON_BORDER_ACTIVE_COLOR = "#2e7031"  # Darker green
CONFIRM_BUTTON_TEXT_COLOR = "#fff"  # White
CONFIRM_BUTTON_TEXT_HOVER_COLOR = "#fff"  # White
CONFIRM_BUTTON_TEXT_ACTIVE_COLOR = "#fff"  # White

CANCEL_BUTTON_COLOR = "#f44336"  # Red
CANCEL_BUTTON_HOVER_COLOR = "#e53935"  # Darker red
CANCEL_BUTTON_ACTIVE_COLOR = "#d32f2f"  # Even darker red
CANCEL_BUTTON_BORDER_COLOR = "#d32f2f"  # Darker red
CANCEL_BUTTON_BORDER_HOVER_COLOR = "#c62828"  # Darker red
CANCEL_BUTTON_BORDER_ACTIVE_COLOR = "#c62828"  # Darker red
CANCEL_BUTTON_TEXT_COLOR = "#fff"  # White
CANCEL_BUTTON_TEXT_HOVER_COLOR = "#fff"  # White
CANCEL_BUTTON_TEXT_ACTIVE_COLOR = "#fff"  # White

